import type { Transaction } from '../types'

/**
 * Demo transactions with realistic categories and subcategories.
 * Useful for populating the dashboard with sample data.
 */
export const demoTransactions: Transaction[] = [
  // --- Salary (income) ---
  {
    id: 1,
    date: '2026-01-31',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 2,
    date: '2026-02-27',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 3,
    date: '2026-03-31',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 4,
    date: '2026-04-30',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 5,
    date: '2026-05-29',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 6,
    date: '2026-06-30',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 7,
    date: '2026-07-31',
    amount: 3200,
    category: 'Salary',
    subcategory: 'Main Job',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: 8,
    date: '2026-03-15',
    amount: 500,
    category: 'Salary',
    subcategory: 'Bonus',
    description: 'Quarterly performance bonus',
    type: 'income',
  },
  {
    id: 9,
    date: '2026-06-15',
    amount: 500,
    category: 'Salary',
    subcategory: 'Bonus',
    description: 'Quarterly performance bonus',
    type: 'income',
  },

  // --- Freelance (income) ---
  {
    id: 10,
    date: '2026-02-10',
    amount: 450,
    category: 'Freelance',
    subcategory: 'Design',
    description: 'Logo design project',
    type: 'income',
  },
  {
    id: 11,
    date: '2026-04-12',
    amount: 600,
    category: 'Freelance',
    subcategory: 'Consulting',
    description: 'Consulting session',
    type: 'income',
  },
  {
    id: 12,
    date: '2026-05-20',
    amount: 350,
    category: 'Freelance',
    subcategory: 'Teaching',
    description: 'Online course tutoring',
    type: 'income',
  },
  {
    id: 13,
    date: '2026-07-08',
    amount: 700,
    category: 'Freelance',
    subcategory: 'Design',
    description: 'Website redesign',
    type: 'income',
  },

  // --- Food (expenses) ---
  {
    id: 14,
    date: '2026-01-05',
    amount: 85.4,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 15,
    date: '2026-01-12',
    amount: 92.15,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 16,
    date: '2026-01-19',
    amount: 78.9,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 17,
    date: '2026-01-26',
    amount: 95.3,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 18,
    date: '2026-02-02',
    amount: 88.75,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 19,
    date: '2026-02-09',
    amount: 76.2,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 20,
    date: '2026-02-16',
    amount: 101.45,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 21,
    date: '2026-02-23',
    amount: 84.6,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 22,
    date: '2026-03-02',
    amount: 91.3,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 23,
    date: '2026-03-09',
    amount: 79.85,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 24,
    date: '2026-03-16',
    amount: 97.5,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 25,
    date: '2026-03-23',
    amount: 86.4,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 26,
    date: '2026-03-30',
    amount: 93.2,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 27,
    date: '2026-04-06',
    amount: 82.7,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 28,
    date: '2026-04-13',
    amount: 89.95,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 29,
    date: '2026-04-20',
    amount: 77.6,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 30,
    date: '2026-04-27',
    amount: 94.8,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 31,
    date: '2026-05-04',
    amount: 83.5,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 32,
    date: '2026-05-11',
    amount: 90.25,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 33,
    date: '2026-05-18',
    amount: 75.9,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 34,
    date: '2026-05-25',
    amount: 98.4,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 35,
    date: '2026-06-01',
    amount: 87.3,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 36,
    date: '2026-06-08',
    amount: 81.65,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 37,
    date: '2026-06-15',
    amount: 96.2,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 38,
    date: '2026-06-22',
    amount: 79.4,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 39,
    date: '2026-06-29',
    amount: 92.75,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 40,
    date: '2026-07-06',
    amount: 85.9,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 41,
    date: '2026-07-13',
    amount: 88.4,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 42,
    date: '2026-07-20',
    amount: 94.1,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 43,
    date: '2026-07-27',
    amount: 80.35,
    category: 'Food',
    subcategory: 'Groceries',
    description: 'Weekly groceries',
    type: 'expense',
  },
  {
    id: 44,
    date: '2026-01-08',
    amount: 45.6,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Dinner with friends',
    type: 'expense',
  },
  {
    id: 45,
    date: '2026-02-14',
    amount: 78.2,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Valentine dinner',
    type: 'expense',
  },
  {
    id: 46,
    date: '2026-03-21',
    amount: 52.4,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Lunch with colleagues',
    type: 'expense',
  },
  {
    id: 47,
    date: '2026-04-18',
    amount: 63.8,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Family dinner',
    type: 'expense',
  },
  {
    id: 48,
    date: '2026-05-16',
    amount: 48.9,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Brunch',
    type: 'expense',
  },
  {
    id: 49,
    date: '2026-06-19',
    amount: 71.5,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Anniversary dinner',
    type: 'expense',
  },
  {
    id: 50,
    date: '2026-07-11',
    amount: 55.3,
    category: 'Food',
    subcategory: 'Restaurants',
    description: 'Dinner out',
    type: 'expense',
  },
  {
    id: 51,
    date: '2026-01-10',
    amount: 4.5,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 52,
    date: '2026-02-11',
    amount: 5.25,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 53,
    date: '2026-03-12',
    amount: 4.75,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 54,
    date: '2026-04-09',
    amount: 5.0,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 55,
    date: '2026-05-14',
    amount: 4.8,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 56,
    date: '2026-06-10',
    amount: 5.1,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 57,
    date: '2026-07-15',
    amount: 4.6,
    category: 'Food',
    subcategory: 'Coffee',
    description: 'Morning coffee',
    type: 'expense',
  },
  {
    id: 58,
    date: '2026-01-22',
    amount: 24.9,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Pizza delivery',
    type: 'expense',
  },
  {
    id: 59,
    date: '2026-02-20',
    amount: 18.75,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Sushi delivery',
    type: 'expense',
  },
  {
    id: 60,
    date: '2026-03-27',
    amount: 22.4,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Burger delivery',
    type: 'expense',
  },
  {
    id: 61,
    date: '2026-04-24',
    amount: 19.6,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Thai food delivery',
    type: 'expense',
  },
  {
    id: 62,
    date: '2026-05-22',
    amount: 26.3,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Pizza delivery',
    type: 'expense',
  },
  {
    id: 63,
    date: '2026-06-26',
    amount: 21.8,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Chinese delivery',
    type: 'expense',
  },
  {
    id: 64,
    date: '2026-07-24',
    amount: 23.5,
    category: 'Food',
    subcategory: 'Delivery',
    description: 'Sushi delivery',
    type: 'expense',
  },

  // --- Transport (expenses) ---
  {
    id: 65,
    date: '2026-01-06',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 66,
    date: '2026-02-03',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 67,
    date: '2026-03-04',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 68,
    date: '2026-04-07',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 69,
    date: '2026-05-05',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 70,
    date: '2026-06-02',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 71,
    date: '2026-07-07',
    amount: 2.75,
    category: 'Transport',
    subcategory: 'Public Transport',
    description: 'Metro card top-up',
    type: 'expense',
  },
  {
    id: 72,
    date: '2026-01-15',
    amount: 12.4,
    category: 'Transport',
    subcategory: 'Taxi',
    description: 'Taxi to airport',
    type: 'expense',
  },
  {
    id: 73,
    date: '2026-03-18',
    amount: 8.9,
    category: 'Transport',
    subcategory: 'Taxi',
    description: 'Taxi home late night',
    type: 'expense',
  },
  {
    id: 74,
    date: '2026-05-28',
    amount: 15.2,
    category: 'Transport',
    subcategory: 'Taxi',
    description: 'Taxi to station',
    type: 'expense',
  },
  {
    id: 75,
    date: '2026-07-17',
    amount: 9.6,
    category: 'Transport',
    subcategory: 'Taxi',
    description: 'Taxi in rain',
    type: 'expense',
  },
  {
    id: 76,
    date: '2026-02-06',
    amount: 45.0,
    category: 'Transport',
    subcategory: 'Gas',
    description: 'Gas refill',
    type: 'expense',
  },
  {
    id: 77,
    date: '2026-04-10',
    amount: 52.3,
    category: 'Transport',
    subcategory: 'Gas',
    description: 'Gas refill',
    type: 'expense',
  },
  {
    id: 78,
    date: '2026-06-12',
    amount: 48.7,
    category: 'Transport',
    subcategory: 'Gas',
    description: 'Gas refill',
    type: 'expense',
  },
  {
    id: 79,
    date: '2026-03-08',
    amount: 3.5,
    category: 'Transport',
    subcategory: 'Parking',
    description: 'City parking',
    type: 'expense',
  },
  {
    id: 80,
    date: '2026-05-15',
    amount: 6.0,
    category: 'Transport',
    subcategory: 'Parking',
    description: 'Airport parking',
    type: 'expense',
  },
  {
    id: 81,
    date: '2026-07-03',
    amount: 4.0,
    category: 'Transport',
    subcategory: 'Parking',
    description: 'Mall parking',
    type: 'expense',
  },

  // --- Entertainment (expenses) ---
  {
    id: 82,
    date: '2026-01-17',
    amount: 12.5,
    category: 'Entertainment',
    subcategory: 'Movies',
    description: 'Cinema tickets',
    type: 'expense',
  },
  {
    id: 83,
    date: '2026-03-14',
    amount: 15.0,
    category: 'Entertainment',
    subcategory: 'Movies',
    description: 'IMAX movie night',
    type: 'expense',
  },
  {
    id: 84,
    date: '2026-05-09',
    amount: 11.0,
    category: 'Entertainment',
    subcategory: 'Movies',
    description: 'Cinema tickets',
    type: 'expense',
  },
  {
    id: 85,
    date: '2026-07-18',
    amount: 14.5,
    category: 'Entertainment',
    subcategory: 'Movies',
    description: 'Summer blockbuster',
    type: 'expense',
  },
  {
    id: 86,
    date: '2026-02-21',
    amount: 59.99,
    category: 'Entertainment',
    subcategory: 'Games',
    description: 'New game purchase',
    type: 'expense',
  },
  {
    id: 87,
    date: '2026-04-25',
    amount: 29.99,
    category: 'Entertainment',
    subcategory: 'Games',
    description: 'Game DLC',
    type: 'expense',
  },
  {
    id: 88,
    date: '2026-06-20',
    amount: 49.99,
    category: 'Entertainment',
    subcategory: 'Games',
    description: 'Steam summer sale',
    type: 'expense',
  },
  {
    id: 89,
    date: '2026-01-28',
    amount: 18.99,
    category: 'Entertainment',
    subcategory: 'Books',
    description: 'Hardcover novel',
    type: 'expense',
  },
  {
    id: 90,
    date: '2026-03-25',
    amount: 12.99,
    category: 'Entertainment',
    subcategory: 'Books',
    description: 'E-book purchase',
    type: 'expense',
  },
  {
    id: 91,
    date: '2026-05-30',
    amount: 24.5,
    category: 'Entertainment',
    subcategory: 'Books',
    description: 'Tech book',
    type: 'expense',
  },
  {
    id: 92,
    date: '2026-07-25',
    amount: 15.99,
    category: 'Entertainment',
    subcategory: 'Books',
    description: 'Paperback',
    type: 'expense',
  },
  {
    id: 93,
    date: '2026-02-28',
    amount: 45.0,
    category: 'Entertainment',
    subcategory: 'Concerts',
    description: 'Concert ticket',
    type: 'expense',
  },
  {
    id: 94,
    date: '2026-06-06',
    amount: 65.0,
    category: 'Entertainment',
    subcategory: 'Concerts',
    description: 'Festival ticket',
    type: 'expense',
  },

  // --- Shopping (expenses) ---
  {
    id: 95,
    date: '2026-01-24',
    amount: 89.9,
    category: 'Shopping',
    subcategory: 'Clothes',
    description: 'Winter jacket',
    type: 'expense',
  },
  {
    id: 96,
    date: '2026-03-28',
    amount: 54.3,
    category: 'Shopping',
    subcategory: 'Clothes',
    description: 'Spring shoes',
    type: 'expense',
  },
  {
    id: 97,
    date: '2026-05-23',
    amount: 42.8,
    category: 'Shopping',
    subcategory: 'Clothes',
    description: 'Summer t-shirts',
    type: 'expense',
  },
  {
    id: 98,
    date: '2026-07-19',
    amount: 67.5,
    category: 'Shopping',
    subcategory: 'Clothes',
    description: 'Sale shopping',
    type: 'expense',
  },
  {
    id: 99,
    date: '2026-02-17',
    amount: 129.99,
    category: 'Shopping',
    subcategory: 'Electronics',
    description: 'Wireless headphones',
    type: 'expense',
  },
  {
    id: 100,
    date: '2026-04-22',
    amount: 39.99,
    category: 'Shopping',
    subcategory: 'Electronics',
    description: 'USB-C hub',
    type: 'expense',
  },
  {
    id: 101,
    date: '2026-06-17',
    amount: 79.99,
    category: 'Shopping',
    subcategory: 'Electronics',
    description: 'Mechanical keyboard',
    type: 'expense',
  },
  {
    id: 102,
    date: '2026-01-31',
    amount: 35.0,
    category: 'Shopping',
    subcategory: 'Home',
    description: 'Kitchen utensils',
    type: 'expense',
  },
  {
    id: 103,
    date: '2026-04-04',
    amount: 120.0,
    category: 'Shopping',
    subcategory: 'Home',
    description: 'New desk lamp',
    type: 'expense',
  },
  {
    id: 104,
    date: '2026-07-04',
    amount: 48.5,
    category: 'Shopping',
    subcategory: 'Home',
    description: 'Bedding set',
    type: 'expense',
  },
  {
    id: 105,
    date: '2026-02-14',
    amount: 25.0,
    category: 'Shopping',
    subcategory: 'Gifts',
    description: 'Valentine gift',
    type: 'expense',
  },
  {
    id: 106,
    date: '2026-05-10',
    amount: 30.0,
    category: 'Shopping',
    subcategory: 'Gifts',
    description: "Mother's day gift",
    type: 'expense',
  },
  {
    id: 107,
    date: '2026-06-21',
    amount: 40.0,
    category: 'Shopping',
    subcategory: 'Gifts',
    description: "Father's day gift",
    type: 'expense',
  },

  // --- Utilities (expenses) ---
  {
    id: 108,
    date: '2026-01-15',
    amount: 85.0,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 109,
    date: '2026-02-15',
    amount: 78.5,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 110,
    date: '2026-03-15',
    amount: 72.3,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 111,
    date: '2026-04-15',
    amount: 68.9,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 112,
    date: '2026-05-15',
    amount: 74.2,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 113,
    date: '2026-06-15',
    amount: 88.6,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 114,
    date: '2026-07-15',
    amount: 95.4,
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: 115,
    date: '2026-01-20',
    amount: 32.0,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 116,
    date: '2026-02-20',
    amount: 30.5,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 117,
    date: '2026-03-20',
    amount: 31.2,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 118,
    date: '2026-04-20',
    amount: 29.8,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 119,
    date: '2026-05-20',
    amount: 33.4,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 120,
    date: '2026-06-20',
    amount: 35.1,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 121,
    date: '2026-07-20',
    amount: 36.7,
    category: 'Utilities',
    subcategory: 'Water',
    description: 'Water bill',
    type: 'expense',
  },
  {
    id: 122,
    date: '2026-01-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 123,
    date: '2026-02-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 124,
    date: '2026-03-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 125,
    date: '2026-04-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 126,
    date: '2026-05-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 127,
    date: '2026-06-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 128,
    date: '2026-07-10',
    amount: 49.99,
    category: 'Utilities',
    subcategory: 'Internet',
    description: 'Internet bill',
    type: 'expense',
  },
  {
    id: 129,
    date: '2026-01-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
  {
    id: 130,
    date: '2026-02-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
  {
    id: 131,
    date: '2026-03-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
  {
    id: 132,
    date: '2026-04-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
  {
    id: 133,
    date: '2026-05-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
  {
    id: 134,
    date: '2026-06-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
  {
    id: 135,
    date: '2026-07-05',
    amount: 25.0,
    category: 'Utilities',
    subcategory: 'Phone',
    description: 'Phone bill',
    type: 'expense',
  },
]